apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-web-go
spec:
  rules:
    - host: example-web-go-<namespace>.<domain>
      http:
        paths:
          - path: /
            backend:
              serviceName: example-web-go
              servicePort: 5000
